### ISSUE TITLE
Tests fail for all tested values other than 12 (Single) 13 (Packed)

### ISSUE THREAD

**Issue by dnbh** [efficient/cuckoofilter#6]
I decided to test bits per item besides 12 (single) and 13 (packed) (number used in example/test.cc, number suggested for packed table in example/test.cc).

I replaced the assert for .Contains with the following after the assertion failed:

``` cpp
    // Check if previously inserted items are in the filter, expected
    // true for all items
    size_t n_found(0);
    for (size_t i = 0; i < num_inserted; i++) {
        n_found += (filter.Contain(i) == cuckoofilter::Ok);
    }
```

I then added the following output below:

``` cpp
// Output the measured true positive rate
    std::cout << "true positive rate is "
              << 100.0 * n_found / total_items
              << "%\n";
    // Outputs 0% true positive for Single Table [6,10,11,13,14,15,24]
    // Outputs 0% true positive for Packed Table [10,11,12,14,15]
```

I added a check to filter_.Add, and it's returning cuckoofilter::Ok every time. The problem seems to be in testing.

Sorry for the trouble!

**Comment by dnbh** [comment]
I want to check in on this. Do you have any plans to support any numbers of bits per item than the defaults? That could make it a more generally useful tool.

**Comment by jbapple-cloudera** [comment]
@dnbh If you look in singletable.h's ReadTag, you will see it only works for bits_per_tag = 2, 4, 8, 12, 16, or 32. Probably there should be a `static_assert` to enforce this.

**Comment by dnbh** [comment]
Good idea. Thanks for pointing that out. Interesting that 12 would be one power of two exception.
