### ISSUE TITLE
Mind if I rewrite to use SIPhash and speed-optimize?

### ISSUE THREAD

**Issue by dave-andersen** [efficient/cuckoofilter#7]
Hi, Bin - do you mind if I rewrite the internals to use SIPhash as the default hash function, and add a few speed optimizations and a benchmark?  I'd like to try to make this even more attractive for people to use out of the box.

**Comment by apc999** [comment]
Sure dave. Go ahead and thanks

I'll also try reorganizing the src code a bit with google style.

**Comment by dave-andersen** [comment]
Obviated by jbapple's PR.  Closing.
